apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ensae-mlops-equipe1
spec:
  project: default
  source:
    repoURL: https://github.com/yann-choho/equipe1-deployment.git
    targetRevision: main
    path: deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: user-choho
  syncPolicy:
    automated:
      selfHeal: true
